# Generated by Django 5.2.8 on 2025-11-24 15:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code IATA')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'aéroport")),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Aéroport',
                'verbose_name_plural': 'Aéroports',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Numéro de passeport')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
            ],
            options={
                'verbose_name': 'Passager',
                'verbose_name_plural': 'Passagers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True, verbose_name='Numéro de vol')),
                ('departure_time', models.DateTimeField(verbose_name='Heure de départ')),
                ('arrival_time', models.DateTimeField(verbose_name="Heure d'arrivée")),
                ('duration', models.DurationField(verbose_name='Durée du vol')),
                ('available_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Sièges disponibles')),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Sièges totaux')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (€)')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('BOARDING', 'Embarquement'), ('DEPARTED', 'Décollé'), ('LANDED', 'Atterri'), ('CANCELLED', 'Annulé')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport', verbose_name="Aéroport d'arrivée")),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport', verbose_name='Aéroport de départ')),
            ],
            options={
                'verbose_name': 'Vol',
                'verbose_name_plural': 'Vols',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=8, unique=True, verbose_name='Référence de réservation')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('number_of_passengers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Nombre de passagers')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (€)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('seat_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Numéro de siège')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight', verbose_name='Vol')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.passenger', verbose_name='Passager')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-booking_date'],
            },
        ),
    ]
