# Generated by Django 5.2.8 on 2025-11-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=20)),
                ('id_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.booking')),
            ],
            options={
                'verbose_name': 'Baggage',
                'verbose_name_plural': 'Baggages',
            },
        ),
    ]
