# Generated by Django 5.2.8 on 2025-11-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_luggage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Luggage',
            new_name='Baggage',
        ),
    ]
