# Generated by Django 5.2.8 on 2025-11-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_luggage_baggage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baggage',
            old_name='id_reservation',
            new_name='booking',
        ),
    ]
