# Generated by Django 5.2.8 on 2025-11-24 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_id_reservation_baggage_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baggage',
            options={'verbose_name': 'Bagage', 'verbose_name_plural': 'Bagages'},
        ),
        migrations.AlterField(
            model_name='baggage',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggages', to='flights.booking', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='baggage',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='baggage',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (kg)'),
        ),
    ]
